export const REGISTRATION = 'REGISTRATION'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const ALL_USER = 'ALL_USER';
export const GET_USER = 'GET_USER';
export const GET_USER_TRANSACTION = 'GET_USER_TRANSACTION';